### ISSUE TITLE
Docs 402 "Payment required" Error

### ISSUE THREAD

**Issue by fvonellerts** [bazzite/nuxt-optimized-images#100]
**Describe the bug**
The documentation is not reachable.

**To Reproduce**
open https://www.bazzite.com/docs/nuxt-optimized-images/

**Comment by juliomrqz** [comment]
Hello @fvonellerts. Thanks for opening the issue and Sorry about that, It's now fixed 🤓.

**Comment by fvonellerts** [comment]
@juliomrqz What can I say, that was fast ;) Thanks!
