### ISSUE TITLE
Background Images

### ISSUE THREAD

**Issue by dolanb12** [bazzite/nuxt-optimized-images#14]
I noticed in the `responsive-loader` docs that CSS background images are supported. Is this true for the entirety of `nuxt-optimized-images`? Or is it mostly limited to `src` as in the examples given?

**Comment by juliomrqz** [comment]
You can use any loader supported by `nuxt-optimized-images` in any component as long as webpack detects it. For CSS background images, you could try this https://github.com/nuxt/nuxt.js/issues/2123.

**Comment by golubvladimir** [comment]
Try this 
`background-image: url("~@/assets/arrow.svg");`
