### ISSUE TITLE
Image component

### ISSUE THREAD

**Issue by alexey-m-ysbm** [bazzite/nuxt-optimized-images#156]
For example, we need a CustomImage component that will nest all of the *require* stuff
Like

```vue
<template>
<picture>
    <source :srcSet="src.webp" type="image/webp" />
    <source :srcSet="src.lqip"/>
    <img :src="src.optimized" :alt="alt" :class="classes" />
</picture>
</template>
```

How can we make sure that we require('img.jpg') only once, passing it as a "src" prop for this component and don't duplicate code everywhere we need all formats of image ?

Example of "src" data for CustomImage
```javascript
{
optimized: require(`${url}`),
webp: require(`${url}?webp`),
lqip: require(`${url}?lqip`),
original: require(`${url}?original`),
}
```

**Comment by juliomrqz** [comment]
For questions, please go to https://spectrum.chat/bazzite/open-source
