### ISSUE TITLE
Ability to use "responsive" loader with webp

### ISSUE THREAD

**Issue by alexey-m-ysbm** [bazzite/nuxt-optimized-images#157]
Is it possibe to use "responsive" resized images and make them "webp"  ?

**Comment by bjesus** [comment]
Also trying to figure this out, as the docs say: 

> responsive-loader will handle all JPEG and PNG images per default, even without an additional query param. Just be aware that you can't use any of the query params @bazzite/nuxt-optimized-images provides anymore

**Comment by juliomrqz** [comment]
For questions, please go to https://spectrum.chat/bazzite/open-source
