### ISSUE TITLE
Webp and resize query params together

### ISSUE THREAD

**Issue by rodrigocarlospires** [bazzite/nuxt-optimized-images#2]
**Describe the bug**
Requiring an image with both **resize** and **webp** query params simultaneously didn't work. I want to export my png image as webp and also resize the exported webp image to different responsive sizes. Is this a bug or that use case is not possible?
Obs: Requires with just one param (?webp or ?resize&sizes...) works normally.

**To Reproduce**

1. Install packages:

`npm install -D @bazzite/nuxt-optimized-images imagemin-mozjpeg imagemin-pngquant imagemin-svgo webp-loader responsive-loader sharp`

2. Require image with both query params:

`const myImage = require('~/assets/images/xxx.png?webp&resize&sizes[]=200&sizes[]=400&sizes[]=800')`

3. Make available on template:

`
export default {
  data() {
    return { myImage }
  }
}
`

4. So in template:

`<img :srcset="myImg.srcSet" :src="myImg.src" />`

**Expected behavior**
So I expected this code render urls to **webp** responsive images:

`<img srcset="/_nuxt/assets/images/xxx--200.webp 200w, /_nuxt/assets/images/xxx--400.webp 400w, /_nuxt/assets/images/faq-balao--800.webp 800w"` ... />

But  I got links to **png** images:

`<img srcset="/_nuxt/assets/images/xxx--200.png 200w, /_nuxt/assets/images/xxx--400.png 400w, /_nuxt/assets/images/faq-balao--800.png 800w"` ... />

Thanks!

**Comment by juliomrqz** [comment]
Hi, @rodrigocarlospires. Currently, [responsive-loader](https://www.npmjs.com/package/responsive-loader) is the module that resizes the images but It [doesn't support WebP yet](https://github.com/herrstucki/responsive-loader/issues/42). There is a PR that try to achieve that https://github.com/herrstucki/responsive-loader/pull/58.

If this gets implemented in responsive-loader, we will adapt it to nuxt-optimized-images.

**Comment by rodrigocarlospires** [comment]
Got it. Thanks @juliomrqz

**Comment by mmoollllee** [comment]
Seems like there is a new one incoming: [herrstucki/responsive-loader#103](https://github.com/herrstucki/responsive-loader/pull/103)
Hope to see this coming :) Thank's for your work!

**Comment by felipeblini** [comment]
> Seems like there is a new one incoming: [herrstucki/responsive-loader#103](https://github.com/herrstucki/responsive-loader/pull/103)
> Hope to see this coming :) Thank's for your work!

I would love to see it working, thank you guys so much for your awesome work, it is helping me a lot!

**Comment by StephanGerbeth** [comment]
for all devs who need this feature, but don't know the alias definition by npm install

````
npm i responsive-loader@npm:responsive-loader-webp@1.2.0-beta.2
````

it works like a charme.

**Comment by TessyPowder** [comment]
@juliomrqz Will you migrate this libary to [responsive-loader-webp](https://github.com/dazuaz/responsive-images-loader) ?
It seems like development will continue there, but i created a [issue](https://github.com/herrstucki/responsive-loader/issues/111) to check if the original author will continue development in responsive-loader.

**Comment by juliomrqz** [comment]
@TessyPowder Sure. Tomorrow I'll push a support for `responsive-loader-well`

**Comment by hug0Hq** [comment]
There is a workaround described in #224 but basically just upgrade responsive-loader to v2.0.0 and use the `?format=webp`

**Comment by TessyPowder** [comment]
> There is a workaround described in #224 but basically just upgrade responsive-loader to v2.0.0 and use the `?format=webp`

I currently use that. It works great

**Comment by TessyPowder** [comment]
But i dont think this repository has to change anything except the documenation, because the webp compatibility will be pushed to the same package on npm by the new maintainer.

**Comment by juliomrqz** [comment]
A new version of `nuxt-optimized-images` ([v1.2.0](https://github.com/juliomrqz/nuxt-optimized-images/releases/tag/v1.2.0)) has been released. It includes support for the latest version of `responsive-loader`. The example and docs have also been updated.
