### ISSUE TITLE
Dynamic src doesn't work

### ISSUE THREAD

**Issue by danielkellyio** [bazzite/nuxt-optimized-images#22]
When hardcoding the image path in the src attribute everything works fine:
`<img src="~/assets/inspired.jpg" />`
but when I use a dynamic src from my components data the image is not linked properly
```
<template>
       <img :src="'~/assets/${img}'" />
</template>
<script>
       export default {
                data(){ return { img: 'inspired.jpg' } }
        }
</script>
```
(this just outputs: `<img src="~/assets/inspired.jpg">`)
I'm running Nuxt 2.7.1

Is it possible to have dynamic src values like this?
Thanks!

**Comment by juliomrqz** [comment]
Hello @danielkellyio. That issue is related to Vue as you can see here:

- https://github.com/nuxt/nuxt.js/issues/2667
- https://github.com/vuejs-templates/webpack/issues/126
