### ISSUE TITLE
Error SVG files on nuxt build when the module is enabled

### ISSUE THREAD

**Issue by brpaz** [bazzite/nuxt-optimized-images#297]
**Describe the bug**
When I run `nuxt build` with the module enabled I get the following error, for all the images it tries to process.

I am using `nuxtjs/svg` module in the project and rendering the images inline in the HTML. Maybe it is related with that.

```
ERROR in ./assets/icons/facebook-share-button.svg?inline
Module build failed (from ./node_modules/vue-svg-loader/index.js):
TypeError: Cannot read property 'children' of undefined
    at /home/bruno/Code/Personal/sites/next.brunopaz.dev/node_modules/svg-to-vue/index.js:70:26
 @ ./components/blog/SocialShare.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/blog/SocialShare.vue?vue&type=script&lang=js&) 45:0-82 50:25-44
 @ ./components/blog/SocialShare.vue?vue&type=script&lang=js&
 @ ./components/blog/SocialShare.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/blog/Post.vue?vue&type=script&lang=js&
 @ ./components/blog/Post.vue?vue&type=script&lang=js&
 @ ./components/blog/Post.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/blog/_slug.vue?vue&type=script&lang=js&
 @ ./pages/blog/_slug.vue?vue&type=script&lang=js&
 @ ./pages/blog/_slug.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js
```

**To Reproduce**
* install this module
* run nuxt build

**Expected behavior**
Build should complete without errors

**Additional context**

 "@nuxtjs/svg": "^0.1.12",

**Comment by juliomrqz** [comment]
Duplicated https://github.com/juliomrqz/nuxt-optimized-images/issues/262

The way `@aceforth/nuxt-optimized-images` and `@nuxtjs/svg` work is by modifying the image loaders for Webpack; both modules have their own way of doing things.

I'm not planning to support other Nuxt modules that update the Webpack loaders; it will significantly increase the codebase maintenance.
