### ISSUE TITLE
Add SQIP alternative to LQIP

### ISSUE THREAD

**Issue by willdante** [bazzite/nuxt-optimized-images#5]
Hi,

I love your project which is very convenient to group mutiple image optimizations.

I'm currently looking to use [SQIP](https://github.com/axe312ger/sqip) instead of LQIP for some images.
There is also a [SQIP loader](https://github.com/EmilTholin/sqip-loader) available.

Could it be integrated to your project in a near future ?

If not, how could I use sqip-loader with nuxt-optimized-images ?

**Comment by juliomrqz** [comment]
Hi, @willdante. [SQIP](https://github.com/axe312ger/sqip) seems to be pretty awesome, we will consider to support it.

But, in the meantime you can use it this way: disable the images you want to [exclude from nuxt-optimized-images](https://www.bazzite.com/docs/nuxt-optimized-images/configuration/#handleimages), then follow [these instructions](https://github.com/EmilTholin/sqip-loader#usage) considering [this example from Nuxt](https://github.com/nuxt/nuxt.js/blob/b83b5675043ebdfec3398bd83fd27dfe77cdd620/examples/web-worker/nuxt.config.js#L44).

**Comment by willdante** [comment]
Hi Julio,

Thanks a lot, I will give it a try.

Best regards.

Marc FILLEUL


Le lun. 8 avr. 2019 à 14:23, Julio Marquez <notifications@github.com> a
écrit :

**Comment by juliomrqz** [comment]
Hi @willdante. SQIP support is now available in the latest version ([v0.2.0](https://www.npmjs.com/package/@bazzite/nuxt-optimized-images/v/0.2.0)) 🎉.
