### ISSUE TITLE
Animated gifs not processing.

### ISSUE THREAD

**Issue by pachiraDIG** [bazzite/nuxt-optimized-images#75]
**Describe the bug**
Animated gifs not processing with imagemin-gifsicle installed. That is, the file size is not changing. Though, the file names are changing so they're being processed somehow... maybe jst not through gifcicle.

**To Reproduce**
Run any animated gif through nuxt-optimized-images using `require()`.

Thanks!

**Comment by juliomrqz** [comment]
Hello, @. 

You detected this bug on Development or Production? Remember that the [images will not get optimized by default when running in development mode](https://www.bazzite.com/docs/nuxt-optimized-images/configuration/#optimizeimagesindev)

**Comment by pachiraDIG** [comment]
In production (universal mode running yarn run generate). I have indeed set
it to process the images in Dev mode as well.
