### ISSUE TITLE
Fix case of srcSet in website

### ISSUE THREAD

**Issue by brunobg** [bazzite/nuxt-optimized-images#99]
**Describe the bug**
https://www.bazzite.com/docs/nuxt-optimized-images/usage/#resize uses `srcset` instead of `srcSet` in the example. The file seems correct in usage.md on github. 

**To Reproduce**
Check https://www.bazzite.com/docs/nuxt-optimized-images/usage/#resize

**Expected behavior**
Documentation should have the correct case. It took me a few minutes to understand what I was doing wrong after following it.

**Comment by juliomrqz** [comment]
Hello @brunobg. Thanks for your bug report, it's now fixed. The changes will be available in the next version released
